version: '3'

services:
  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb+srv://nandita:nandita123@cluster0.6gyyf.mongodb.net/
      - JWT_SECRET_KEY=keyisworking
      - JWT_EXPIRES=10d
      - COOKIE_EXPIRE=7
      - CLOUDINARY_CLIENT_NAME=dvbycvgxo
      - CLOUDINARY_CLIENT_API=731961421713156
      - CLOUDINARY_CLIENT_SECRET=vT9TEZyabOIHrho8fEDD6HmLOgk
      - FRONTEND_URL=http://65.0.85.33
    networks:
      - app-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
